export const LOCATIONS_PENDING = 'LOCATIONS_PENDING'
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCESS'
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED'
export const LOCATION_UPDATE_SUCCESS = 'LOCATION_UPDATE_SUCCESS'
export const LOCATION_DELETE_SUCCESS = 'LOCATION_DELETE_SUCCESS'
export const NEW_LOCATION_SUCCESS = 'NEW_LOCATION_SUCCESS'
export const ONE_LOCATION_SUCCESS = 'ONE_LOCATION_SUCCESS'

export const BASE_URL = 'http://localhost:8080/locations'